---
title: "Data Cleaning 3 Year"
author: "Julio"
date: '`r Sys.Date()`'
output: html_document
---


```{r}
## (a)
library(haven)
library(dplyr)
library(lubridate)
library(stringr)

## Data saving (commented out) and csv loading 
# LLCP2016 <- read_xpt("LLCP2016.XPT")
# write.csv(LLCP2016, file = "LLCP2016")
LLCP2016 <- read.csv("LLCP2016")

# LLCP2018 <- read_xpt("LLCP2018.XPT")
# write.csv(LLCP2018, file = "LLCP2018")
LLCP2018 <- read.csv("LLCP2018")

# LLCP2020 <- read_xpt("LLCP2020.XPT")
# write.csv(LLCP2020, file = "LLCP2020")
LLCP2020 <- read.csv("LLCP2020")

LLCP2016$datetime <- paste0(LLCP2016$IMONTH,"-", LLCP2016$IDAY, "-", LLCP2016$IYEAR)
LLCP2016$date <- as.Date(LLCP2016$datetime, format = c("%m-%d-%Y"))

## I will recycle this variable to cut off jan-april (prepandemic)
## NOTE: the data collected goes into Feb of the following year, not just Jan!
startpandemic <- as.Date("04-14-2016", format = "%m-%d-%Y")
tester1 <- subset(LLCP2016, LLCP2016$date > startpandemic)

LLCP2018$datetime <- paste0(LLCP2018$IMONTH,"-", LLCP2018$IDAY, "-", LLCP2018$IYEAR)
LLCP2018$date <- as.Date(LLCP2018$datetime, format = c("%m-%d-%Y"))
startpandemic <- as.Date("04-14-2018", format = "%m-%d-%Y")
tester2 <- subset(LLCP2018, LLCP2018$date > startpandemic)

LLCP2020$datetime <- paste0(LLCP2020$IMONTH,"-", LLCP2020$IDAY, "-", LLCP2020$IYEAR)
LLCP2020$date <- as.Date(LLCP2020$datetime, format = c("%m-%d-%Y"))
startpandemic <- as.Date("04-14-2020", format = "%m-%d-%Y")
tester3 <- subset(LLCP2020, LLCP2020$date > startpandemic)


tester1 <- subset(tester1, X_HISPANC == 1)
tester2 <- subset(tester2, X_HISPANC == 1)
tester3 <- subset(tester3, X_HISPANC == 1)

tester1 <- tester1[, c("DIABETE3", "HEIGHT3", "WEIGHT2", "CVDCRHD4", "X_TOTINDA", "IYEAR", "date",
                       "X_HISPANC", "SEX", "X_AGE_G")]
tester2 <- tester2[, c("DIABETE3", "HEIGHT3", "WEIGHT2", "CVDCRHD4", "X_TOTINDA", "IYEAR", "date",
                       "X_HISPANC", "SEX1", "X_AGE_G")]
tester3 <- tester3[, c("DIABETE4", "HEIGHT3", "WEIGHT2", "CVDCRHD4", "X_TOTINDA", "IYEAR", "date",
                       "X_HISPANC", "X_SEX", "X_AGE_G")]


## rename diabetes variable to same thing
tester1 <- rename(tester1, diabetes = DIABETE3)
tester2 <- rename(tester2, diabetes = DIABETE3)
tester3 <- rename(tester3, diabetes = DIABETE4)

## rename sex variable
tester1 <- rename(tester1, sex = SEX)
tester2 <- rename(tester2, sex = SEX1)
tester3 <- rename(tester3, sex = X_SEX)

## combine data
testercomplete <- rbind(tester1, tester2)
testercomplete <- rbind(testercomplete, tester3)
```

## Data Cleaning
```{r}
testercomplete$HEIGHT3[testercomplete$HEIGHT3 == 99 | testercomplete$HEIGHT3 == 77] <- NA

testercomplete$WEIGHT2[testercomplete$WEIGHT2 == 9999 | testercomplete$WEIGHT2 == 7777] <- NA


weightcalc<- function(weight) {
    if(weight %in% 49:0777) {
       return(weight)
} else if (weight %in% 9022:9353) {
       return((weight - 9000)*2.2)
} else {
  return(NA)
}
}

testercomplete$newweight <- sapply(testercomplete$WEIGHT2, function(x) weightcalc(x)) 

heightcalc<- function(height) {
    if(height %in% 199:712) {
       return((((height %/% 100) * 12) + (height %% 100)))
} else if (height %in% 9061:9998) {
       return((height - 9000)/2.54)
} else {
  return(NA)
}
}
## be careful for outliers and wrongly inputted data
## there are also A LOT of implausible looking values - Hafsa what you think?
testercomplete$newheight <- sapply(testercomplete$HEIGHT3, function(x) heightcalc(x)) 

## New weight is now in pounds!
testercomplete <- testercomplete %>% 
  mutate(bmi = (newweight / newheight^2) *703)

testercomplete$bmicat[testercomplete$bmi < 18.5] <- 1
testercomplete$bmicat[testercomplete$bmi >= 18.5 & testercomplete$bmi < 25] <- 2
testercomplete$bmicat[testercomplete$bmi >= 25 & testercomplete$bmi < 30] <- 3
testercomplete$bmicat[testercomplete$bmi >= 30] <- 4
testercomplete$bmicat <- factor(testercomplete$bmicat,
                               levels = 1:4,
                               labels = c("<18.5", "18.5-24", "25-29", "≥30"))

## New diabetes variable named diabebin
testercomplete$diabebin[testercomplete$diabetes == 9 | testercomplete$diabetes == 7] <- NA
testercomplete$diabebin[testercomplete$diabetes %in% 2:4] <- 0
testercomplete$diabebin[testercomplete$diabetes == 1] <- 1
testercomplete$diabebin <- factor(testercomplete$diabebin,
                               levels = 0:1,
                               labels = c("No Diabetes", "Diabetes"))

## New high bmi variable named bmihigh
testercomplete$bmihigh[testercomplete$bmi >= 25] <- 1
testercomplete$bmihigh[testercomplete$bmi < 25] <- 0
testercomplete$bmihigh <- factor(testercomplete$bmihigh,
                               levels = 0:1,
                               labels = c("BMI < 25", "BMI ≥ 25"))

## 
testercomplete$X_AGE_G <- factor(testercomplete$X_AGE_G,
                               levels = 1:6,
                               labels = c("18-24", "25-34", "35-44", "45-54", "55-64", "65+"))

## factored interview year variable
testercomplete$year <- factor(testercomplete$IYEAR,
                               levels = 2016:2021,
                               labels = c("2016", "2017", "2018", "2019", "2020", "2021"))

## Combined year variable
testercomplete$yearsurv[testercomplete$year %in% 2016:2017] <- 1
testercomplete$yearsurv[testercomplete$year %in% 2018:2019] <- 2
testercomplete$yearsurv[testercomplete$year %in% 2020:2021] <- 3
testercomplete$yearsurv <- factor(testercomplete$yearsurv,
                               levels = 1:3,
                               labels = c("2016", "2018", "2020"))

## New CVD variable named cvdbin
testercomplete$cvdbin[testercomplete$CVDCRHD4 == 9 | testercomplete$CVDCRHD4 == 7] <- NA
testercomplete$cvdbin[testercomplete$CVDCRHD4 == 2] <- 0
testercomplete$cvdbin[testercomplete$CVDCRHD4 == 1] <- 1
testercomplete$cvdbin <- factor(testercomplete$cvdbin,
                               levels = 0:1,
                               labels = c("No CVD", "CVD"))

## New PA variable named activbin
testercomplete$activbin[testercomplete$X_TOTINDA == 9 | testercomplete$X_TOTINDA == 7] <- NA
testercomplete$activbin[testercomplete$X_TOTINDA == 2] <- 0
testercomplete$activbin[testercomplete$X_TOTINDA == 1] <- 1
testercomplete$activbin <- factor(testercomplete$activbin,
                               levels = 0:1,
                               labels = c("No Activity", "Some Activity"))

## sex variable
testercomplete$sex[testercomplete$sex == 9 | testercomplete$sex == 7] <- NA
testercomplete$sex[testercomplete$sex == 2] <- 2
testercomplete$sex[testercomplete$sex == 1] <- 1
testercomplete$sex <- factor(testercomplete$sex,
                               levels = 1:2,
                               labels = c("Male", "Female"))

## Age cutoff variable 
testercomplete <- testercomplete %>% 
  mutate(agecat = case_when(X_AGE_G == "18-24" | X_AGE_G == "25-34" |X_AGE_G == "35-44" ~ 1,
                            X_AGE_G == "45-54" | X_AGE_G == "55-64" |X_AGE_G == "65+" ~ 2))
testercomplete$agecat <- factor(testercomplete$agecat,
                               levels = 1:2,
                               labels = c("<45", "45+"))
```


## Creating the Table 
```{r}
library(gtsummary)

## Table with all variables (maybe not use)
testercomplete %>% select(diabebin, HEIGHT3, WEIGHT2, cvdbin, activbin, year, date, bmihigh) %>%
 tbl_summary(by = "year",missing = "ifany",
 digits = list(all_categorical() ~ c(0,1)), 
 label = list(diabebin ~ "Diabetes",
              HEIGHT3 ~ "Height",
              WEIGHT2 ~ "Weight",
              cvdbin ~ "CVD", 
              activbin ~ "Physical Activity",
              year ~ "Year", 
              date ~ "Date",
              bmihigh = "BMI ≥ 25")) %>%
 modify_header(label = "**Variable**")

## Table with necessary variables
table1 <- testercomplete %>% select(yearsurv, sex, X_AGE_G, diabebin, cvdbin, bmicat, activbin) %>%
 tbl_summary(by = "yearsurv",missing = "ifany",
 digits = list(all_categorical() ~ c(0,1)), 
 label = list(sex ~ "Sex",
              X_AGE_G ~ "Age Group",
              diabebin ~ "Diabetes",
              cvdbin ~ "Cardiovascular Diesease", 
              bmicat ~ "BMI Category",
              activbin ~ "Physical Activity")) %>%
 modify_header(label = "**Variable**") %>%
  modify_caption("**Table 1. National Characteristics Among Latin Population for Physical Activity, Diabetes, Cardiovascular Disease, Body Mass Index, Age Group, Sex, Based on BRFSS Interview Years 2016, 2018 & 2020**") %>%
  bold_labels() 

```


## Analysis for Table 2
```{r}
library(epiR)
install.packages("exact2x2")
library(exact2x2)

## this is for confounding only (prob need to input more confounders later)

## The way I am creating this variable is omitting one year (this one omits 2020)
testercomplete <- testercomplete %>% mutate(
  yearcont = case_when(
    yearsurv == 2016 ~ 1,
    yearsurv == 2018 ~ 2,
    yearsurv == 2020 ~ NA,
    TRUE ~ NA_real_)) # catch-all condition for any other values
testercomplete$yearcont <- factor(testercomplete$yearcont,
                          levels = c(1, 2, NA),
                          labels = c("2016",
                                     "2018")) 
testercomplete <- testercomplete %>% mutate(
  yearcase = case_when(
    yearsurv == 2016 ~ 1,
    yearsurv == 2018 ~ NA,
    yearsurv == 2020 ~ 2,
    TRUE ~ NA_real_)) # catch-all condition for any other values
testercomplete$yearcase <- factor(testercomplete$yearcase,
                          levels = c(1, 2, NA),
                          labels = c("2016",
                                     "2020")) 

strat1 <- xtabs(~yearcont + activbin + sex + agecat, data = testercomplete)
strat2 <- xtabs(~yearcase + activbin + sex + agecat, data = testercomplete)

#array_1 <- array(strat_1,
array1 <- array(strat1,
               dim = c(2,2,4),
               list(exposure = c(2016, 2018),
                    outcomes = c('No Activity', 'Some Activity'),
                    confounders = 1:4))
array2 <- array(strat2,
               dim = c(2,2,4),
               list(exposure = c(2016, 2020),
                    outcomes = c('No Activity', 'Some Activity'),
                    confounders = 1:4))

epi.2by2(array1, method = 'cross.sectional')
epi.2by2(array2, method = 'cross.sectional')


## For effect modification of BMI

strat_bmihigh_1 <- xtabs(~yearcont + activbin + sex + agecat, data = testercomplete, subset = bmihigh == "BMI < 25")
strat_bmilow_1 <- xtabs(~yearcont + activbin + sex + agecat, data = testercomplete, subset = bmihigh == "BMI ≥ 25")

strat_bmihigh_2 <- xtabs(~yearcase + activbin + sex + agecat, data = testercomplete, subset = bmihigh == "BMI < 25")
strat_bmilow_2 <- xtabs(~yearcase + activbin + sex + agecat, data = testercomplete, subset = bmihigh == "BMI ≥ 25")

array_bmihigh_1 <- array(strat_bmihigh_1,
                      dim = c(2,2,4),
                      list(exposure = c(2016, 2018),
                           outcomes = c('No Activity', 'Some Activity'),
                           confounders = 1:4))
array_bmilow_1 <- array(strat_bmilow_1,
                      dim = c(2,2,4),
                      list(exposure = c(2016, 2018),
                           outcomes = c('No Activity', 'Some Activity'),
                           confounders = 1:4))
array_bmihigh_2 <- array(strat_bmihigh_2,
                      dim = c(2,2,4),
                      list(exposure = c(2016, 2020),
                           outcomes = c('No Activity', 'Some Activity'),
                           confounders = 1:4))
array_bmilow_2 <- array(strat_bmilow_2,
                      dim = c(2,2,4),
                      list(exposure = c(2016, 2020),
                           outcomes = c('No Activity', 'Some Activity'),
                           confounders = 1:4))



epi.2by2(array_bmihigh_1, method = 'cross.sectional')
epi.2by2(array_bmilow_1, method = 'cross.sectional')
epi.2by2(array_bmihigh_2, method = 'cross.sectional')
epi.2by2(array_bmilow_2, method = 'cross.sectional')


## Diabetes Effect Modification
strat_Diabn_1 <- xtabs(~yearcont + activbin + sex + agecat, data = testercomplete, subset = diabebin == "No Diabetes")
strat_Diaby_1 <- xtabs(~yearcont + activbin + sex + agecat, data = testercomplete, subset = diabebin == "Diabetes")
strat_Diabn_2 <- xtabs(~yearcase + activbin + sex + agecat, data = testercomplete, subset = diabebin == "No Diabetes")
strat_Diaby_2 <- xtabs(~yearcase + activbin + sex + agecat, data = testercomplete, subset = diabebin == "Diabetes")
array_Diabn_1 <- array(strat_Diabn_1,
                      dim = c(2,2,4),
                      list(exposure = c(2016, 2018),
                           outcomes = c('No Activity', 'Some Activity'),
                           confounders = 1:4))
array_Diaby_1 <- array(strat_Diaby_1,
                      dim = c(2,2,4),
                      list(exposure = c(2016, 2018),
                           outcomes = c('No Activity', 'Some Activity'),
                           confounders = 1:4))
array_Diabn_2 <- array(strat_Diabn_2,
                      dim = c(2,2,4),
                      list(exposure = c(2016, 2020),
                           outcomes = c('No Activity', 'Some Activity'),
                           confounders = 1:4))
array_Diaby_2 <- array(strat_Diaby_2,
                      dim = c(2,2,4),
                      list(exposure = c(2016, 2020),
                           outcomes = c('No Activity', 'Some Activity'),
                           confounders = 1:4))

epi.2by2(array_Diabn_1, method = 'cross.sectional')
epi.2by2(array_Diaby_1, method = 'cross.sectional')
epi.2by2(array_Diabn_2, method = 'cross.sectional')
epi.2by2(array_Diaby_2, method = 'cross.sectional')


## Effect Modification for CVD
strat_CVDn_1 <- xtabs(~yearcont + activbin + sex + agecat, data = testercomplete, subset = cvdbin == "No CVD")
strat_CVDy_1 <- xtabs(~yearcont + activbin + sex + agecat, data = testercomplete, subset = cvdbin == "CVD")
strat_CVDn_2 <- xtabs(~yearcase + activbin + sex + agecat, data = testercomplete, subset = cvdbin == "No CVD")
strat_CVDy_2 <- xtabs(~yearcase + activbin + sex + agecat, data = testercomplete, subset = cvdbin == "CVD")

array_CVDn_1 <- array(strat_CVDn_1,
                      dim = c(2,2,4),
                      list(exposure = c(2016, 2018),
                           outcomes = c('No Activity', 'Some Activity'),
                           confounders = 1:4))
array_CVDy_1 <- array(strat_CVDy_1,
                      dim = c(2,2,4),
                      list(exposure = c(2016, 2018),
                           outcomes = c('No Activity', 'Some Activity'),
                           confounders = 1:4))
array_CVDn_2 <- array(strat_CVDn_2,
                      dim = c(2,2,4),
                      list(exposure = c(2016, 2020),
                           outcomes = c('No Activity', 'Some Activity'),
                           confounders = 1:4))
array_CVDy_2 <- array(strat_CVDy_2,
                      dim = c(2,2,4),
                      list(exposure = c(2016, 2020),
                           outcomes = c('No Activity', 'Some Activity'),
                           confounders = 1:4))
epi.2by2(array_CVDn_1, method = 'cross.sectional')
epi.2by2(array_CVDy_1, method = 'cross.sectional')
epi.2by2(array_CVDn_2, method = 'cross.sectional')
epi.2by2(array_CVDy_2, method = 'cross.sectional')
```



